#!/usr/bin/zsh

# Patrick Conley <pconley@uvic.ca>
# Last modified: 2012 Feb 13
#
# Summary: A prompt that looks something like this:
#
# Script exit with error: test
# Bellgrove:3 [13 Feb 12:04] -> exit 4                            ~/bin/assist
# Bellgrove:2 [13 Feb 12:14] exit: 4 -> mkdir .zsh                           ~

function zsh-prompt-read-error # {{{1
{

   unset error

   error_file=/tmp/pconley-script-error
   if [ ! -f $error_file ]
   then
      exit
   fi
   
   error=$( cat $error_file )
   rm $error_file
   echo "
%{$fg_bold[green]%}Script exit with error:%{$reset_color%} $error
%{%}"

} # }}}1

ps1=( "%{$fg_bold[red]%}"
      "%m"                                     # hostname
      "%{$reset_color%}"

      "%(2L.:%{$fg[yellow]$bg_bold[red]%}%L%{$reset_color%}.)" # shell depth

      " ["
      "%{$fg_bold[yellow]%}"
      "%D{%d %b %H:%M}"                        # date & time
      "%{$reset_color%}"
      "] "

      "%(0?..exit: %{$bg[red]%}%?%{$reset_color%} )" # exit status

      "%{%(!.$fg_bold[red].$fg_bold[cyan])%}"
      "-> "                                    # prompt char
      "%{$reset_color%}"
    )
PS1='$(zsh-prompt-read-error)${(j::)ps1}'

ps2=( "%{$fg_bold[cyan]%}"
      "%_ "
      "%{$fg_bold[red]%}"
      "> "
      "%{$reset_color%}"
    )
PS2=${(j::)ps2}

rprompt=( "%{$fg[green]%}"
          "%42<...<%~"
          "%{$reset_color%}"
        )
RPROMPT=${(j::)rprompt}
